### PR TITLE
Game Proposal

### PR DESCRIPTION
**Pull request by CastielM**
Have created a new folder for a game called Single Combat, a tetris-esque puzzle game. Added game proposal markdown document.

### CODE REVIEW

**Comment by CastielM** [comment]
[Create Design Proposal for Tetris Game](https://trello.com/c/jNnDwCfn/267-create-design-proposal-for-tetris-game)

**Comment by CastielM** [comment]
Originally removed the auto generated files but have reverted this commit as not sure of the impact this will have. It may generate a new set of files titled 'SingleCombat' because the file name has changed, and leave the other one as well. We can remove the one with the old name later if it does this.

**Comment by CastielM** [comment]
I've just added in 8 .png files into the Images folder for the Single Combat game - basic artwork to be used for the moment.

**Comment by CastielM** [comment]
[Develop basic art for Single Combat (Tetris) Game](https://trello.com/c/UrG9LByj/317-develop-basic-art-for-single-combat-tetris-game)

**Comment by CastielM** [comment]
[Set up game files and basic configuration for Single Combat (Tetris) Game](https://trello.com/c/GhVXM09o/318-set-up-game-files-and-basic-configuration-for-single-combat-tetris-game)

**Comment by CastielM** [comment]
[Single combat - create a first sprite and get it to be able to 'fall' onto the board](https://trello.com/c/DESa2Eth/355-single-combat-create-a-first-sprite-and-get-it-to-be-able-to-fall-onto-the-board)

**Review by omckeon — APPROVED** [review]
Good start. I would like to see some sort of design diagram as well - can be added in later.

**Pull request merged**
