### PR TITLE
Update repo link for Below The Surface

### PR DESCRIPTION
**Pull request by MHLoppy**
# Description

Updates the readme for Below The Surface to reference the current repo (`thoth-tech/arcade-games`) instead of its original repo.

I've specifically chosen not to update the config.txt for Below The Surface, Asteroids, and DXBallGame as it's unclear whether these files are intended to be used beyond their prior purpose in the original submission of these games.

## Type of change

- [x] Documentation (update or new)

## How Has This Been Tested?

N/A

## Testing Checklist

N/A

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~ (N/A)
- [ ] ~~I have performed a self-review of my own code~~ (N/A)
- [ ] ~~I have commented my code in hard-to-understand areas~~ (N/A)
- [ ] ~~I have made corresponding changes to the documentation~~ (N/A)
- [x] My changes generate no new warnings
- [x] I have requested a review from my team on ~~the Pull Request~~ Teams

### CODE REVIEW

**Comment by MHLoppy** [comment]
[All games - update outdated documentation](https://trello.com/c/oyOHqXDK/492-all-games-update-outdated-documentation)

**Review by CastielM — COMMENTED** [review]
Heyo! I think the cd command needs to include /games/BelowTheSurface in order to be in the right folder to compile the game?

**Comment by MHLoppy** [comment]
> Heyo! I think the cd command needs to include /games/BelowTheSurface in order to be in the right folder to compile the game?

X_X you're totally right, I wasn't even paying attention to the rest of the command.

**Comment by CastielM** [comment]
Needs conflicts with the bot's build files resolved but otherwise looks good

**Comment by AmberPotion** [comment]
Rip, conflicts have returned xD

**Pull request merged**
