### PR TITLE
Update Venture Adventure's debugging output to check for state changes

### PR DESCRIPTION
**Pull request by MHLoppy**
# Description

The current console debugging dumps a bunch of info every single cycle, which floods the console with mostly low-value information. Whilst whether the current debugging infodump is actually useful or not can be debated, in the meantime we can at least increase the signal-to-noise-ratio of the output by tracking the game state and comparing the current cycle's state vs the previous cycle's state.

If no change has been made, the infodump is not sent and a "waiting for changes..." message is sent once. Once the (tracked) state changes again, the updated infodump is sent.

Castiel mentioned how it was nice to be able to turn the debugging on/off by changing one line of code, so I've maintained this feature using a bool check before running the new code (change the bool to turn off the debugging output).

## Type of change

- [x] Documentation (?)

## How Has This Been Tested?

I built and ran Venture Adventure with the updated code and monitored the console output.

## Testing Checklist

N/A

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation*
- [x] My changes generate no new warnings
- [x] I ~~have requested~~ will request a review from the team on Teams etc

\* _I'm working on some documentation updates elsewhere, so will include a note about flipping the bool in that documentation._

### CODE REVIEW

**Comment by MHLoppy** [comment]
[Venture Adventure - update debugging to not repeat stale messages](https://trello.com/c/E0VsljaI/590-venture-adventure-update-debugging-to-not-repeat-stale-messages)

**Review by CastielM — APPROVED** [review]
Looks good! Works a lot better to actually be able to stop and read the output!
And definitely nice to still be able to toggle it with once change. 

I do think a lot of the output there is useful for debugging based on what I've worked on, but there's certainly room for improvement and/or making it easier to customize depending on what someone's working on. 

We can ignore the error about the missing 'back' file, as I've resolved that in another PR. Looks like the libpng/sRGB  warning is here too, not sure if that's a local thing to me or not but doesn't seem to cause any issues.

**Comment by CastielM** [comment]
Looks good still after conflicts resolved

**Comment by omckeon** [comment]
@MHLoppy I've just updated the PingPong config.txt file to try to resolve the workflow failing. Try pulling that change into your fork/branch and commit that change, then you can message me on Teams to let me know and I can re-run the jobs. :)

**Pull request merged**
