### PR TITLE
Venture Adventure - Small refactor (part 5)

### PR DESCRIPTION
**Pull request by MHLoppy**
# Description

While getting working on Venture Adventure again, I felt like there was low-hanging fruit available to refactor that would make future work easier. I've split this work into several parts of related changes to make for smaller PRs that are easier to review.

This is part 5/5 **(building on the previous changes made in the chain)** and is focused on removing the use of `using namespace std`.

## Type of change

- [x] Other: refactor

## How Has This Been Tested?

I recompiled the game and played through it, ensuring that all refactored functionality threw no errors and worked the same as pre-refactor.

## Testing Checklist

- [x] Played through all of level 1
- [x] Played through all of level 2
- [x] Played start of level 1 after cycling through main menu after completing both level 1 + level 2

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I'll notify my team when the PR is ready to review

### CODE REVIEW

**Comment by MHLoppy** [comment]
As a note, the existing swap function was commented out rather than removed, which makes it slightly easier to understand the change. Once happy with the PR, it would be better to actually remove the code (maybe I can throw it in there between the first and second reviews - it obviously won't affect functionality).

**Comment by lexlam1524** [comment]
the game look very good, and it will be great if it can walk faster or add a run function, because for the play experience, it spends lot of time if I go the wrong way.

**Comment by MHLoppy** [comment]
> the game look very good, and it will be great if it can walk faster or add a run function, because for the play experience, it spends lot of time if I go the wrong way.

Please try to keep review comments related to the scope of the pull request, as otherwise the actual contents of the pull request aren't really being reviewed.

The feedback you've given can probably be turned into its own task on Planner though, and would be especially relevant if the map size is ever increased! Feel free to make the card, and if you or someone else on the team want to tackle it we can give it a shot. Hopefully it wouldn't be too hard to implement?

**Comment by MHLoppy** [comment]
**Superceded by #228 after merge conflicts**

**Comment by AmberPotion** [comment]
> the game look very good, and it will be great if it can walk faster or add a run function, because for the play experience, it spends lot of time if I go the wrong way.

Agreed with Mark's comment - If you intend to review his PR's before mentor reviewing, please provide feedback on the actual PR's content, not the overall game feel itself.

**Comment by AmberPotion** [comment]
Cool part 5

**Pull request closed without merging**
