### PR TITLE
BelowTheSurface - fix/players-attack

### PR DESCRIPTION
**Pull request by zhusim222**
Below the surface - what's going on with the player's attack, 

this was fixed as the code within the collision file did not perform the required task.
collision file was changed to reflect the desired damage and killing mechanic in the game

Fixes # (issue)

The palyer attack did nothing except the level 10 boss, the code had it remove HP but nothing happens when the enemy gets to 0 HP. this has now been fixed with if 0 then die, if higher it will do damage.
[ x ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_
the attack was tested on each monster to ensure it worked, including enemies with more than 1 HP. went through each level with monsters and used the attack key to ensure their damage and HP matched against their death.

## Testing Checklist

tested in MYSYS2

## Checklist

[ X] My code follows the style guidelines of this project
[ X] I have performed a self-review of my own code
[ X] I have commented my code in hard-to-understand areas
[X ] I have made corresponding changes to the documentation
[ X] My changes generate no new warnings
[ X] I have requested a review from Tien on the Pull Request

### CODE REVIEW

**Comment by zhusim222** [comment]
[Below The Surface - what's going on with the player's attacks?](https://trello.com/c/lrCgevK5/527-below-the-surface-whats-going-on-with-the-players-attacks)

**Review by MHLoppy — CHANGES_REQUESTED** [review]
Can you change the check on line 342 to be `<= 0` instead of `== 0`? The original check can lead to unintended bugs if other sources of damage reduce HP below 0.

**Comment by zhusim222** [comment]
Thank you Mark, have made the changes

**Comment by zhusim222** [comment]
Answering Marks question
Attack
The technical change itself looks good.

Do you have any comment on whether allowing the attack to affect non-boss enemies makes the game much easier? I know for example that the fast moving snake things are quite hard to kill via jumping -- basically: does this make the game too easy?

I don't believe it will affect the gameplay much, yes it will make the monsters easier to kill and avoid. but i believe the main focus on the game should be puzzle solving with some action on the side.

**Review by MHLoppy — CHANGES_REQUESTED** [review]
The gist of the change looks good and works fine in testing. However can you change the SFX line to run its usual `if (!sound_effect_playing())` check first? Sorry for not noticing its absence in my earlier review on the double-PR - that's my bad as a reviewer.
```
if (!sound_effect_playing("EnemyDead"))
    play_sound_effect("EnemyDead");
```
I think this is the normal practice for playing sounds in SplashKit to avoid accidentally calling SFX more than once.

**Comment by AmberPotion** [comment]
Fixed by [#232](https://github.com/thoth-tech/arcade-games/pull/232)

**Pull request closed without merging**
