### PR TITLE
Below The Surface Credits Fix

### PR DESCRIPTION
**Pull request by DerDieDasDeakin**
Fixes the issue of the credits screen being cut off. Manual adjustments added to ensure the credits appear properly as the current implementation was not working correctly.

# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change._

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?
Tested in game after compilation. 
_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

## Checklist

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by DerDieDasDeakin** [comment]
[Below The Surface - Credits cut off](https://trello.com/c/2nB3n7hz/539-below-the-surface-credits-cut-off)

**Comment by DerDieDasDeakin** [comment]
[Below The Surface - Credits cut off](https://trello.com/c/2nB3n7hz/539-below-the-surface-credits-cut-off)

**Review by MHLoppy — CHANGES_REQUESTED** [review]
The updated credits screen looks great on my end, though it'd be a good idea for one of us to double-check how it looks on the arcade machines next semester since that's ultimately where we care most about how the games run / look.

image

For your newly-introduced variables `vertical_shift` and `bitmap_vertical_shift` I think they'd be easier to work with if these values were positive and then a switch between add/subtract happens where they're being called as needed:

* On line 1051, instead of subtracting a negative number (a double-negative), but this could instead be changed to adding a positive number.
* On line 1059, instead of adding a negative number, this could instead be subtracting a positive number.

Because the two variables are used in close proximity to each other, it'd also be a good idea to rename `vertical_shift` to something more self-explanatory like `text_vertical_shift`, similarly to how you've already done this for `bitmap_vertical_shift`.

**Comment by AmberPotion** [comment]
Superseded by a

**Comment by AmberPotion** [comment]
Superseded by [#231](https://github.com/thoth-tech/arcade-games/pull/231).

**Pull request closed without merging**
