### PR TITLE
Runner Dash - Added difficulty settings

### PR DESCRIPTION
**Pull request by AnotherNewName**
(Jaron Chen 220296732)
- Added a setting for enemy count, ranging from 1 to 4.
- Added a toggle to enable/disable enemy diagonal movement.
- Added a setting to change the chance for the enemies to skip their turn.
- Added an interface for the user to change the three new difficulty settings.
- Changed the player movement code to fix a bug that caused an invalid input from the user to 'use up' the players turn.

### CODE REVIEW

**Comment by AnotherNewName** [comment]
[Adding Difficulty settings to Runner Dash](https://trello.com/c/curgHz4Q/346-adding-difficulty-settings-to-runner-dash)

**Comment by AnotherNewName** [comment]
[Adding Difficulty settings to Runner Dash](https://trello.com/c/curgHz4Q/346-adding-difficulty-settings-to-runner-dash)

**Review by omckeon — CHANGES_REQUESTED** [review]
In "public void move(bool EnemyMoveDiagonal, int EnemySkipTurnPercent, int EnemyCount)":
- Why did you change the switch statement to if statements? Switch works better here.
- Why did you remove the try/catch and exceptions? (These are better than using break and Console.WriteLine).
- You seem to have removed the functionality to exit (it was with X key I think). Add this back in (and you can check other games such as Asteroids to use the same key for this game).

**Comment by AnotherNewName** [comment]
Implemented the requested changes.
For the questions about removing the switch and the try/catch, it was honestly more about how i worked on the task, in that i removed that chunk of code and rewrote it; there was no specific reason. In hindsight, i should have approached it differently. As such, i have re-implemented the switch, the try/catch, and functionality to return to the main menu with "x".

**Review by omckeon — APPROVED** [review]
Much better

**Pull request merged**
