### PR TITLE
Added new game to arcade games (Sky Surge)

### PR DESCRIPTION
**Pull request by ayanmasood**
Added documentation and game files to the directory. Classes for player input handling and enemy AI for functionality along with collision detection and sprites.

### CODE REVIEW

**Comment by ayanmasood** [comment]
[Create new game proposal/documentation](https://trello.com/c/D7ItXARP/349-create-new-game-proposal-documentation)

**Comment by ayanmasood** [comment]
[Setup Player and Game logic (Sky Surge)](https://trello.com/c/GLXviGNy/396-setup-player-and-game-logic-sky-surge)

**Comment by ayanmasood** [comment]
[Enemy AI and Collision Detection (Sky Surge)](https://trello.com/c/KfbDOWzM/410-enemy-ai-and-collision-detection-sky-surge)

**Review by omckeon — CHANGES_REQUESTED** [review]
I have tried a few things to get this game to work, and am still running into issues.

You need to do more extensive testing of this game before making the PR.

A few notes:
- fields should start with an underscore.
- make sure to assign a value to all fields (don't ignore any warnings).
- Rename the folder to remove the space.
- Make sure to use png files that don't have a background. Have a look into https://www.getpaint.net/ for a tool to remove the background using the "magic" tool.
- Make sure the size of the images is correct for the screen size (they were very big and distorted for me) - possibly need to check the screen size used in a game such as Asteroids).
- The Main game loop should have methods for "Update", "Draw" and "HandleInput", not just Update.
- In your ReadMe file - add the controls to use for the game, and possibly a screenshot of what the main game area should look like.

**Comment by ayanmasood** [comment]
[Create Level, Update Start Menu and Fix Bugs (Sky Surge)](https://trello.com/c/7Kr2KEmR/418-create-level-update-start-menu-and-fix-bugs-sky-surge)

**Comment by ayanmasood** [comment]
[Documentation on Explanation of Classes and Bugs Identified/Features to Add](https://trello.com/c/c709L6uU/422-documentation-on-explanation-of-classes-and-bugs-identified-features-to-add)

**Review by omckeon — APPROVED** [review]
Good work. This is a nice simple starting point for the game.

**Pull request merged**
