### PR TITLE
Object Oriented Development for Single Combat Game

### PR DESCRIPTION
**Pull request by CastielM**
Have separated out my initial code into classes including a 'block' and 'board' class. Have also created a 2D array/vector with smart pointers to start being able to generate/place the blocks on the board. Code still works as intended, better than it did initially even, with much better separation of classes for the object oriented development approach. Still more work to be done going forward in separating code out in classes (e.g., final block class will not have user input in it). Next steps are to allow successive blocks to be placed.

### CODE REVIEW

**Comment by CastielM** [comment]
[Single combat - turn block sprite into an object that can be reused](https://trello.com/c/LU1V7MAt/356-single-combat-turn-block-sprite-into-an-object-that-can-be-reused)

**Comment by CastielM** [comment]
[Single combat game - create a board class to further compartmentalize code](https://trello.com/c/A3LcSS1m/386-single-combat-game-create-a-board-class-to-further-compartmentalize-code)

**Comment by CastielM** [comment]
Commits since original request have not been added as Trello cards yet. Got carried away improving the OOD design of the code and working on the 2D array. Logic is close to allow blocks to be placed anywhere on the board, but not quite. Last 2 commits [0c36663] and [2c1b492] are both close in a different way. Issue I believe is in the 'board.cpp' file and will be to do with the activeRow and currentDestination variables, possibly in the changeDestination or update methods

**Comment by CastielM** [comment]
[Single Combat Game - get 2D array working to allow blocks to stack](https://trello.com/c/IHrL7rBo/395-single-combat-game-get-2d-array-working-to-allow-blocks-to-stack)

**Comment by CastielM** [comment]
Fixed the bug. There is more work to do in board class with stacking but going to create a new Trello task. Currently you can stack blocks in all columns vertically and they will add to 2D array correctly, however there is nothing to stop blocks moving left and right into already filled columns so that will be the next task.

**Comment by CastielM** [comment]
[Single Combat Game - need to update development documentation with details of work so far](https://trello.com/c/Dhdk5aD4/387-single-combat-game-need-to-update-development-documentation-with-details-of-work-so-far)

**Comment by CastielM** [comment]
Actually took me quite a few hours (3-4) putting this documentation altogether but I hope is it thorough. Some of it was catching up to fix my comments and make notes about decisions I’d already made, others was about outlining expectations around contributing to this project, making a workflow, a place to report bugs and suggestions, class descriptions and decisions, and other game design docs such as info about phases, a list of game mechanics that are currently planned and a rough order for them, aka the ‘working document'.

I am very keen for feedback on what people think of the documentation, will it work? How can I improve it and ensure people read it and use it? My aim to make contributing to this project as smooth and consistent as possible for people.

**Comment by CastielM** [comment]
New updated UML diagram added for Trello task. This a working diagram, not a final one (because it will develop as the game develop), but as it stands this is what exists/is being created in the code currently. Hard to foresee some of the classes that will be required but I will update this as development progresses and the structure becomes more clear. I anticipate that there will be more classes needed when features are added later on, but these are the main classes and their methods that are currently needed. Essentially following an Agile/iterative development process for the UML diagram.

**Comment by CastielM** [comment]
[Single combat - UML diagram](https://trello.com/c/QVvPLH90/360-single-combat-uml-diagram)

**Comment by CastielM** [comment]
[Single Combat Game - add functionality to prevent blocks from being moved left or right if another block is already there](https://trello.com/c/Em5rE6Vl/406-single-combat-game-add-functionality-to-prevent-blocks-from-being-moved-left-or-right-if-another-block-is-already-there)

**Review by omckeon — APPROVED** [review]
Good start!

Note: In T1 2024 things will be changing slightly. Part of this change is that any games that are worked on will need to be done procedurally (with structs) rather than OOP with classes. And will need to be able to be understood by Intro level students.
If you decide to work on the game further over the break - I suggest that you update the code to be procedural (and snake_case), remove the pointers/shared pointer code and any other more complex code so that the code is using functionality that was taught in Intro, or that is included in the SplashKit functionality (it can be heavy with SplashKit rather than avoiding).
Then the next steps would be to create tutorials to accompany the game.

**Comment by omckeon** [comment]
Also - Make sure to use proper PR Template in T1 2024 (or any new PRs this trimester)

**Pull request merged**
