### PR TITLE
BelowTheSurface - fix/Game-controls

### PR DESCRIPTION
**Pull request by zhusim222**
# Game control screen in main menu/sub menu extra.

-added an extra menu button under "extra" sub menu. this alows the player the select the controls button which will take them to a screen to show all the controls in BOTH the PC version and the arcade machine version

also changed the keyboard layout for 1 player and 2 player. as when 2 players both played at same time it conflicted the buttons.

Fixes 2 issues

Type of change

- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I have tested it out to ensure all the functions work properly. so in this case i tested both characters in single player and 2 player to ensure the controls working as intended.

also tested out the menu button which shows the player the controls.

## Testing Checklist

Tested in MYSYS2

## Checklist

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have requested a review from Tien and peers. on the Pull Request

### CODE REVIEW

**Comment by zhusim222** [comment]
[Below The Surface - tell the player the controls](https://trello.com/c/gQirboYo/497-below-the-surface-tell-the-player-the-controls)

**Review by MHLoppy — APPROVED** [review]
The added controls screen is a good starting point, and maybe the team next semester can look at some further improvements.

image

image

For keyboard players (which, granted, might be a less important demographic target than arcade machine players), using CTRL and ALT for attack/use and jump is a bit awkward because they're not side-by-side (there isn't a natural resting point that will have a player's index and middle finger on both buttons). Obviously having P1 and P2 clash over controls (as we had before) is even worse though, so this is an improvement over that.

Suggestions for next sem:
* Look into letting P1 use less cramped controls in 1P-only mode (such as being allowed to use P2's attack/use and jump buttons).
* Find a keyboard control scheme for P1 and P2 that lets them have their attack/use and jump buttons side-by-side.

[This post by Damian Yerrick](https://gamedev.stackexchange.com/questions/86477/key-mapping-for-a-2-players-game) has a couple of helpful notes relating to the topic of sharing keyboard controls between 2 players. I'll copy the bulk of that below for posterity:

> Let the user configure the bindings from an options menu in the application. Players might be using QWERTZ (German) or AZERTY (French) layout keyboards, Dvorak layout keyboards, joysticks, etc., and they don't want to have to learn Yet Another Config File Language.
>
>But still, a lot of players will want to jump in and play without changing any settings. So you still have to choose good defaults and show them to the player when the game starts. Consider this:
>
> * Right player moves with arrow keys and does actions with apostrophe and Enter.
> * Left player moves with RDFG and does actions with Z and X. Do not straddle the line between TGB and YHN because a lot of "ergonomic" keyboards split the left hand and right hand keys here.
> * Single player mode should allow input from either side, so that players used to the common emulator default of arrows and ZX can jump in.
> * Common actions can be done while the game is paused. Common back/pause is Esc.
> * Show these keys to the players at the bottom of the first screen of the game, so that the player can get used to them before being in any real danger.

**Comment by zhusim222** [comment]
Thank you for your input Mark, yes it was quite hard to find the correct solution. in the future if i can get the chance i will try your suggestions.

**Comment by AmberPotion** [comment]
Fixed by #235

**Pull request closed without merging**
