### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by CastielM**
# Description

Added some documentation to assist with working on this game next trimester. Includes information about creating a new level, helpful tips (including debugging and testing tips) and enhancement ideas. This documentation somewhat relates to code in PR 200 that hasn't been merged yet.

## Type of change
- [X] Documentation (update or new)

### CODE REVIEW

**Comment by CastielM** [comment]
[Documentation for Venture Adventure](https://trello.com/c/48vgN3bd/536-documentation-for-venture-adventure)

**Review by MHLoppy — APPROVED** [review]
There's a typo in "assets" in HelpfulTips.md but otherwise this looks good, and on behalf of future contributors is a much appreciated addition.

**Comment by CastielM** [comment]
Easy, can fix that one, and also add your idea about the gems :)

**Comment by MHLoppy** [comment]
> In **game.cpp** there is a variable called **debugeasymode**. This can be set to *true* to make levels only generate one gem, making them easier to complete. Remember to change this back before committing anything.

I've been scammed!!1!1

**Comment by AmberPotion** [comment]
> > In **game.cpp** there is a variable called **debugeasymode**. This can be set to _true_ to make levels only generate one gem, making them easier to complete. Remember to change this back before committing anything.
> 
> I've been scammed!!1!1

XD? Huh?

**Pull request merged**
