### PR TITLE
Bug Fixes / Minor Adjustments

### PR DESCRIPTION
**Pull request by CastielM**
# Description

Minor bug fixes and quality of life adjustments:

- Fixed level 3 not appearing and added a total levels constant to allow easier addition of new levels
- Adjusted controls to be consistent with player 1 controls on the arcade machine
- Added button to restart current level as found that it was possible to soft lock by moving boxes that prevented gem collection
- Added text to HUD to include controls
- Fixed bug where you couldn’t exit game while on the start screen

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Have run the compiled and run the game using "skm g++ *.cpp -o game"

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have requested a review from Game Development Team on the Pull Request

### CODE REVIEW

**Comment by CastielM** [comment]
[Venue Adventure minor bug fixes/quality of life adjusments](https://trello.com/c/LLyuJi3t/519-venue-adventure-minor-bug-fixes-quality-of-life-adjusments)

**Comment by CastielM** [comment]
# Description

Worked on improving UI for password entry for Below The Surface. Need assistance with a new bug it's generated where the 'EXIT' option doesn't always work. Noticed a quirk with the password checking as well where the password is 'blank' until you reach the 3rd character where it automatically adds in _ for missing characters. This seems like it has some relevant as the EXIT option starts working again when you return to less than 3 characters and the password is blank again.

- Added automatic 'confirm' when a password is correct (think the bug is related to this)
- Added error sound when password is wrong
- Added error message when password is wrong
- Automatically deletes last character entered when wrong so player doesn't need to navigate to DEL option, and to avoid looped audio.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Compiled with skm g++ -std=c++23 *.cpp -o game. Note the difference with the C++ version, not sure if this is an issue with just my machine being outdated or if everyone will encounter compile issues without it


## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [X] I have requested a review from Game Development Team on the Pull Request

**Comment by CastielM** [comment]
[Below The Surface - improve UX of entering fifth letter of password](https://trello.com/c/XmlFjDZR/524-below-the-surface-improve-ux-of-entering-fifth-letter-of-password)

**Comment by CastielM** [comment]
Fixed the issue I noted above.

**Comment by CastielM** [comment]
Removed the code that required C++23, the normal compile command "skm g++ *.cpp -o game" should work now.

**Comment by p4stoboy** [comment]
Changes against [this ticket](https://trello.com/c/XmlFjDZR) @ [this commit](https://github.com/CastielM/capstone-games/commit/4a908501cbd33030d2f9bb99f7f72dca7bf105a5) are fine and ticket has been moved to mentor review.

The input pattern surrounding this fix should be looked at more closely (ie - use 2d array to store and inform drawing of alphabet / index it directly instead of looping over 1d structure to check is_selected() property of every item??) -> food for another ticket.

It is my understanding that there are still tickets to be reviewed attached to this PR so this is not ready to be merged yet.

**Comment by p4stoboy** [comment]
Commits:
@CastielM
[CastielM fixed level 3 not appearing and added constant for total num…](https://github.com/thoth-tech/arcade-games/pull/187/commits/8bd49b3b1abeff86cae29312750cc6d227bb04b1) 
[8bd49b3](https://github.com/thoth-tech/arcade-games/pull/187/commits/8bd49b3b1abeff86cae29312750cc6d227bb04b1)
@CastielM
[CastielM added text for controls to HUD](https://github.com/thoth-tech/arcade-games/pull/187/commits/cfa4f7eec52ed44e31184ea1b1b03058ee88e2c8)
[cfa4f7e](https://github.com/thoth-tech/arcade-games/pull/187/commits/cfa4f7eec52ed44e31184ea1b1b03058ee88e2c8)
@CastielM
[CastielM added ability to reset current level in case of soft lock (I…](https://github.com/thoth-tech/arcade-games/pull/187/commits/5d25791914ea062c2cc432576b48f7f61cd91e82) 
[5d25791](https://github.com/thoth-tech/arcade-games/pull/187/commits/5d25791914ea062c2cc432576b48f7f61cd91e82)
@CastielM
[CastielM fixed bug where you couldn't exit game while on the start sc…](https://github.com/thoth-tech/arcade-games/pull/187/commits/0ee17d5f090fe23845583279c74d3a410fa124e8) 
[0ee17d5](https://github.com/thoth-tech/arcade-games/pull/187/commits/0ee17d5f090fe23845583279c74d3a410fa124e8)
@CastielM
[CastielM changed controls to use WASD which should be consistent with…](https://github.com/thoth-tech/arcade-games/pull/187/commits/e7522c1ec47166bbe2cc70a8a0b59af76e3a6d3e) 
[e7522c1](https://github.com/thoth-tech/arcade-games/pull/187/commits/e7522c1ec47166bbe2cc70a8a0b59af76e3a6d3e)
@CastielM
[CastielM changed start key to be enter instead of space key, which sh…](https://github.com/thoth-tech/arcade-games/pull/187/commits/3dd55dc9ba45a74cac8d42eeeee832c997578b98) 
[3dd55dc](https://github.com/thoth-tech/arcade-games/pull/187/commits/3dd55dc9ba45a74cac8d42eeeee832c997578b98)

Against ticket: https://trello.com/c/LLyuJi3t

Are all fine / good non-structural changes that significantly improve QOL and maintainability.

Workflow checks are breaking but as far as I can tell this is likely a broader issue (certainly nothing in these commits should be contributing to this).

Passing this ticket to Tien for sign off.

**Review by p4stoboy — APPROVED** [review]

**Pull request merged**
