### PR TITLE
BelowTheSurface - fix/backstory

### PR DESCRIPTION
**Pull request by zhusim222**
# Description
Backstory (access via main menu → extras, goes too fast at first to read. I reckon this should only progress via a button to give player as long as they need to read.

Fixes # (issue)

To combat this issue i have changed the timer from 8s to 45seconds. this allows the player to have time to read through each slide. ive also added a text at the bottom "press key to continue..." this allows the player to press enter or ctrl keys when done and it will proceed to the next page.
also while i was looking the first slide "backstory" was not properly centered and had some of the T cut off, this was fixed by moving it downwards.

_Please delete options that are not relevant._

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

tested on MYSYS2 and ensured that it worked fully each time. the required text was centered and the timer for 45 seconds was correct on each slide.

## Checklist

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have requested a review from Tien on the Pull Request

### CODE REVIEW

**Comment by zhusim222** [comment]
[Below The Surface - Backstory goes too fast](https://trello.com/c/dCncdJ1u/538-below-the-surface-backstory-goes-too-fast)

**Review by MHLoppy — APPROVED** [review]
45 seconds might be a tad far in the other direction, but with the press-to-continue that's not a big deal.

If you have a minute to spare it'd be good to fix up some of the formatting in those lines, like using `foo - bar` instead of the existing `foo- bar` since that helps readability. (I know that was already in there before you got to it so it's not your fault!).

Otherwise looks fine, approved.

**Comment by zhusim222** [comment]
Thanks Mark

**Comment by AmberPotion** [comment]
Fixed by #234

**Pull request closed without merging**
