### PR TITLE
 Updated code for car-race

### PR DESCRIPTION
**Pull request by KhushiLaddi08**
# CAR-RACING

## Changes Made

- New Player Mode Added : One and Two 
- New Scenery has been added
- New Levels has been pushed from slower to faster
- New Powerups has been added to make it interesting
-  New Voices has been added
- Pause Function has been added with the P button
- At last barricaded has been added with little space so that player can face more difficulties while playing.

## Compile 
- skm clang++ *.cpp -o abc is used for compilation
- ./abc.exe is used for output

### CODE REVIEW

**Comment by KhushiLaddi08** [comment]
[Updated Car-Race code](https://trello.com/c/BUmAvGs0/599-updated-car-race-code)

**Comment by omckeon** [comment]
@KhushiLaddi08 You need to update the PR Description with the details of what this PR is including.

**Comment by KhushiLaddi08** [comment]
> @KhushiLaddi08 You need to update the PR Description with the details of what this PR is including.

@omckeon Ma'am I have update my Description :)

**Comment by KhushiLaddi08** [comment]
Maam, I have updated description with the changes made in the game

**Comment by omckeon** [comment]
@KhushiLaddi08 
The PR Description should be using the template (found in the .github folder).

Also, to fix the failing checks: Your forked repo needs to include all of the branches from this repo, not just the main branch. Add in the other branches and re-run the checks.

**Pull request closed without merging**
