### PR TITLE
Car Race - Update the Homescreen with New Controls

### PR DESCRIPTION
**Pull request by DerDieDasDeakin**
Updates the Homescreen with New ‘W' and 'S’ Controls.

### CODE REVIEW

**Comment by DerDieDasDeakin** [comment]
[Car Race - Update the Homescreen with New Controls](https://trello.com/c/yin2hp7u/419-car-race-update-the-homescreen-with-new-controls)

**Comment by omckeon** [comment]
I am confused - there is no functionality for W and S keys in this game?

**Review by omckeon — APPROVED** [review]
Looks good.

**Comment by omckeon** [comment]
I tried to run the compile games script again to resolve the conflicts which unfortunately didn't work. Can you resolve these conflicts and then message me on Teams once this is done.

**Comment by omckeon** [comment]
Can't seem to resolve the conflicts, so I will close this PR, and you can try another PR from a new branch (make sure to use git pull before making the commit)

**Pull request closed without merging**
