### PR TITLE
Below The Surface - Increased contrast between background and cockroach/water rat

### PR DESCRIPTION
**Pull request by AnotherNewName**
Changed the cockroach colour scheme to a lighter shade of brown for more contrast with the background.
Added an outline to water rat (final boss rat) to more easily distinguish between dark portions of the rat and the background.

### CODE REVIEW

**Comment by AnotherNewName** [comment]
[Below The Surface - Change colour schemes of specific enemies](https://trello.com/c/2uj6ZGKt/359-below-the-surface-change-colour-schemes-of-specific-enemies)

**Comment by CastielM** [comment]
Definitely a lot easier to see the roach which is awesome! The rat is easier to see, but not quite sure how I feel about the outline, feels like it detracts from the style a bit. I wonder if there’s a way to remove the darker grey background layer that hovers at the player’s eyeline. Is there a reason it’s there, rather than the background being all the lighter grey, do we know?

**Comment by AnotherNewName** [comment]
I've reverted the water rat texture change and have made the shades of grey in the background a little lighter, though I'm hesitant to make more significant changes to the background. 
I feel that the background colour needs to be a mid/dark grey to match the dark sewer aesthetic the game is going for. Also, the multiple shades of grey for the background is because using a single shade of grey makes the background feel like a placeholder texture that exists only because the real background texture is not finished.

**Comment by CastielM** [comment]
This solution works better to provide contrast to the rat in my opinion!

> I've reverted the water rat texture change and have made the shades of grey in the background a little lighter, though I'm hesitant to make more significant changes to the background. I feel that the background colour needs to be a mid/dark grey to match the dark sewer aesthetic the game is going for. Also, the multiple shades of grey for the background is because using a single shade of grey makes the background feel like a placeholder texture that exists only because the real background texture is not finished.

**Comment by omckeon** [comment]
Nice!

**Pull request merged**
