### PR TITLE
Splash kit mario game 

### PR DESCRIPTION
**Pull request by kay-kaushik**
# Description

This pull request introduces a Mario game code to the Arcade Games repository. The code encompasses essential game development concepts such as resource loading, movement logic, animations, physics, and camera management. By integrating this Mario game, we enhance the repository's offerings with a practical example, providing learners and developers with a hands-on experience in game development using SplashKit. This addition aligns with the repository's goal of offering diverse and instructive examples to the community, fostering learning and innovation in game development.

## How Has This Been Tested?

I have manually tested the code on my system.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from Olivia on the Pull Request

### CODE REVIEW

**Comment by kay-kaushik** [comment]
[Code for Mario-Like Game Tutorial Using SplashKit](https://trello.com/c/X1p8spcK/606-code-for-mario-like-game-tutorial-using-splashkit)

**Comment by kay-kaushik** [comment]
[Code for Mario-Like Game Tutorial Using SplashKit](https://trello.com/c/X1p8spcK/606-code-for-mario-like-game-tutorial-using-splashkit)

**Comment by lexlam1524** [comment]
[Naming refactor of ExecutionEnvironment and related code](https://trello.com/c/mqHADqTC/584-naming-refactor-of-executionenvironment-and-related-code)

**Comment by DerDieDasDeakin** [comment]
**Splashkit Mario game Peer Review**
This is a great start! I've run this one through a bit and I think this is a solid foundation for a game that can be worked on throughout the next trimester. The movement currently is a bit slow, I'm not too sure if it's just a problem on my end, but the movement sometimes looks like it is running in slow-mo. There's some minor glitching at the moment with the platform, as you sometimes don't fall down once jumping off and continue walking through the air. Your work with the animation looks great currently, I think the background and sprites really showcase what this game can become with some extra work. I can't find any documentation for this game anywhere, so it would be a great idea to get that done as well, since it means other students can help progress the development of this along the way and it helps provide some context on what the end goal for this project is. It may be too late into the trimester to work on that now, but it would be a great way to start the next trimester. I think it would be a good idea to move this to the "in progress games" folder instead of the "games" folder, since this still has a long way to go and can't be judged as a completed game yet. In future, it would be good to break up your work on the game into smaller PRs, that way it can be evaluated a bit easier and its easier for other students to help contribute, too. Overall, I think this is a good start but will need a lot of attention next trimester to get it into a more playable and complete state.

**Review by omckeon — APPROVED** [review]
Code lacks proper structuring, functional decomposition and modularisation, but it is a good start for the games team to continue working with in future.

**Pull request merged**
