### PR TITLE
CAR RACING

### PR DESCRIPTION
**Pull request by KhushiLaddi08**
**INTRODUCTION**
The Car Race game developed by me using the Splash Kit SDK. The game is a basic arcade-style car game where the player's objective is to navigate a car on a road while avoiding collisions with other cars.

### CODE REVIEW

**Comment by KhushiLaddi08** [comment]
[Racing game Mechanics](https://trello.com/c/EiPCOMOa/173-racing-game-mechanics)

**Comment by KhushiLaddi08** [comment]
[Bug Testing and Finalization](https://trello.com/c/zJDAuhjR/177-bug-testing-and-finalization)

**Comment by KhushiLaddi08** [comment]
[Car Racing On Github](https://trello.com/c/MTHrRrTE/185-car-racing-on-github)

**Comment by KhushiLaddi08** [comment]
[Visual Aspect and Functionality](https://trello.com/c/pwuWTfoh/146-visual-aspect-and-functionality)

**Review by DaGoblin — APPROVED** [review]
The game works and runs ok.
Controls need to be updated for Arcade Machines

**Pull request merged**
